name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 
        with:
          persist-credentials: false

      - name: Install and Build 🔧 
        run: |
          mkdir -p output/${GITHUB_REF##*/}
          pip3 install wheel
          pip3 install setuptools
          pip3 install -r Utils/requirements.txt
          python3 Utils/build.py build-output
          cp -r build-output/* output/${GITHUB_REF##*/}/
          python3 Utils/jinjatest.py ${GITHUB_REF##*/}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages 
          FOLDER: ./output 
          CLEAN: false 